<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
	<TargetFramework>net9.0</TargetFramework>
	<TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
	<EnableDynamicLoading>true</EnableDynamicLoading>
	<AssemblyName>$(MSBuildProjectName)</AssemblyName>
	<AssemblyTitle></AssemblyTitle>
	<RootNamespace>$(MSBuildProjectName.Replace(" ","_"))</RootNamespace>
	<ImplicitUsings>enable</ImplicitUsings>
	<OutputType>Library</OutputType>
	<PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Nono\localization\**" />
  </ItemGroup>
  <ItemGroup>
	<Reference Include="0Harmony">
		<HintPath>F:\steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
	</Reference>
	<Reference Include="GodotSharp">
		<HintPath>F:\steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll</HintPath>
	</Reference>
	<Reference Include="sts2">
		<HintPath>F:\steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
	</Reference>
	<Reference Include="STS2-RitsuLib">
	  <HintPath>RitsuLib\STS2-RitsuLib.dll</HintPath>
	</Reference>
  </ItemGroup>
	
	
	
	
</Project>